### ISSUE TITLE
This happens when i compile in 1.0.6.3

### ISSUE THREAD

**Issue by CorraAshu** [marv7000/AssetBankPlugin#1]
If i compile without the assetbankplugin it works fine. Also if i comment out that line it compiles but i can't find how to open the assetbanks in BF4 and only see a animations option window in the options menu

![Screenshot 2023-07-11 012633](https://github.com/marv7000/AssetBankPlugin/assets/11359715/9bb79a74-c315-47d2-9138-b66c4586b0f1)

**Comment by marv7000** [comment]
Fixed with fd88e55fc79c8bcdb38161dbd0f1e713a9946331, Git seems to have ignored this change. 
Previewing the contents of AssetBanks is a work in progress and not really functional UI wise. The plugin will dump all valid AnimationAssets from banks and save them to the export directory.

You can only see the contents in the debugger at the moment.
